const statusOptions = [
  { value: "present", label: "Present" },
  { value: "absent", label: "Absent" },
  { value: "late", label: "Late" },
  { value: "excused", label: "Excused" },
  { value: "sick_leave", label: "Sick Leave" },
];

const paymentStatusOptions = [
  { value: "pending", label: "Pending" },
  { value: "partial", label: "Partial" },
  { value: "paid", label: "Paid" },
  { value: "overdue", label: "Overdue" },
  { value: "cancelled", label: "Cancelled" },
];

const paymentMethodOptions = [
  { value: "cash", label: "Cash" },
  { value: "bank", label: "Bank" },
  { value: "card", label: "Card" },
  { value: "mobile_money", label: "Mobile Money" },
  { value: "other", label: "Other" },
];

const assessmentTypes = [
  { value: "quiz", label: "Quiz" },
  { value: "homework", label: "Homework" },
  { value: "assignment", label: "Assignment" },
  { value: "midterm", label: "Midterm" },
  { value: "final_exam", label: "Final Exam" },
  { value: "oral_exam", label: "Oral Exam" },
  { value: "practical_exam", label: "Practical Exam" },
  { value: "monthly_test", label: "Monthly Test" },
];

const inventoryCategories = [
  { value: "books", label: "Books" },
  { value: "notebooks", label: "Notebooks" },
  { value: "pens", label: "Pens" },
  { value: "pencils", label: "Pencils" },
  { value: "bags", label: "Bags" },
  { value: "uniforms", label: "Uniforms" },
  { value: "copies", label: "Copies" },
  { value: "markers", label: "Markers" },
  { value: "other", label: "Other" },
];

export const reportConfigs = {
  attendance: {
    slug: "attendance",
    title: "Attendance Report",
    tableTitle: "Attendance Records",
    endpoint: "/v1/reports/attendance/",
    description: "Analyze daily attendance by date, class, course, teacher, student, and status.",
    chartKey: "attendance_trends",
    chartTitle: "Attendance Trends",
    chartType: "line",
    stats: [
      { key: "total_records", label: "Records", accent: "border-sky-500" },
      { key: "present", label: "Present", accent: "border-emerald-500" },
      { key: "absent", label: "Absent", accent: "border-red-500" },
      { key: "attendance_percentage", label: "Attendance %", accent: "border-cyan-600" },
    ],
    filters: [
      { key: "course", label: "Course name" },
      { key: "batch", label: "Class / batch name" },
      { key: "teacher", label: "Teacher name" },
      { key: "student", label: "Student name" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
    ],
    columns: [
      { key: "date", label: "Date" },
      { key: "student__name", label: "Student" },
      { key: "class_fk__name", label: "Class" },
      { key: "course__name", label: "Course" },
      { key: "teacher__full_name", label: "Teacher" },
      { key: "status", label: "Status" },
    ],
  },
  assessments: {
    slug: "assessments",
    title: "Assessments Report",
    endpoint: "/v1/reports/assessments/",
    description: "Track assessment outcomes, grades, pass rates, teachers, and course performance.",
    chartKey: "assessment_trends",
    chartTitle: "Assessment Result Trends",
    stats: [
      { key: "results", label: "Results", accent: "border-sky-500" },
      { key: "passed", label: "Passed", accent: "border-emerald-500" },
      { key: "failed", label: "Failed", accent: "border-red-500" },
      { key: "average_percentage", label: "Average %", accent: "border-violet-500" },
    ],
    filters: [
      { key: "course", label: "Course name" },
      { key: "teacher", label: "Teacher name" },
      { key: "assessment_type", label: "Assessment Type", type: "select", options: assessmentTypes },
      { key: "student", label: "Student name" },
    ],
    columns: [
      { key: "assessment__title", label: "Assessment" },
      { key: "assessment__assessment_date", label: "Date" },
      { key: "assessment__assessment_type", label: "Type" },
      { key: "student__name", label: "Student" },
      { key: "course__name", label: "Course" },
      { key: "teacher__full_name", label: "Teacher" },
      { key: "percentage", label: "Percentage" },
      { key: "grade", label: "Grade" },
    ],
  },
  fees: {
    slug: "fees",
    title: "Fees Report",
    endpoint: "/v1/reports/fees/",
    description: "Review fee invoices, collections, balances, payment status, plans, and courses.",
    chartKey: "fee_collection",
    chartTitle: "Fee Collection Chart",
    stats: [
      { key: "invoices", label: "Invoices", accent: "border-sky-500" },
      { key: "expected", label: "Expected", accent: "border-indigo-500", format: "money" },
      { key: "collected", label: "Collected", accent: "border-emerald-500", format: "money" },
      { key: "pending", label: "Pending", accent: "border-orange-500", format: "money" },
    ],
    filters: [
      { key: "student", label: "Student name" },
      { key: "payment_status", label: "Payment Status", type: "select", options: paymentStatusOptions },
      { key: "fee_plan", label: "Fee plan course" },
      { key: "course", label: "Course name" },
      { key: "batch", label: "Class / batch name" },
    ],
    columns: [
      { key: "invoice_number", label: "Invoice" },
      { key: "student__name", label: "Student" },
      { key: "course__name", label: "Course" },
      { key: "due_date", label: "Due Date" },
      { key: "final_amount", label: "Amount" },
      { key: "paid_amount", label: "Paid" },
      { key: "balance", label: "Balance" },
      { key: "status", label: "Status" },
    ],
  },
  revenue: {
    slug: "revenue",
    title: "Revenue Report",
    endpoint: "/v1/reports/revenue/",
    description: "Monitor revenue sources, payment methods, and monthly or yearly collections.",
    chartKey: "monthly_revenue",
    chartTitle: "Monthly Revenue",
    stats: [
      { key: "payments", label: "Payments", accent: "border-sky-500" },
      { key: "total_revenue", label: "Revenue", accent: "border-emerald-500", format: "money" },
      { key: "average_payment", label: "Average Payment", accent: "border-cyan-600", format: "money" },
    ],
    filters: [
      { key: "source", label: "Revenue source course" },
      { key: "payment_method", label: "Payment Method", type: "select", options: paymentMethodOptions },
      { key: "cashier", label: "Cashier username" },
      { key: "grouping", label: "Grouping", type: "select", options: [{ value: "monthly", label: "Monthly" }, { value: "yearly", label: "Yearly" }] },
    ],
    columns: [
      { key: "receipt_number", label: "Receipt" },
      { key: "invoice__invoice_number", label: "Invoice" },
      { key: "student__name", label: "Student" },
      { key: "payment_date", label: "Date" },
      { key: "payment_method", label: "Method" },
      { key: "amount_paid", label: "Amount" },
      { key: "received_by__username", label: "Cashier" },
    ],
  },
  students: {
    slug: "students",
    title: "Students Report",
    endpoint: "/v1/reports/students/",
    description: "Analyze enrollment totals by course, status, gender, and enrollment date range.",
    chartKey: "student_enrollment",
    chartTitle: "Student Enrollment Chart",
    stats: [
      { key: "students", label: "Students", accent: "border-sky-500" },
      { key: "active", label: "Active", accent: "border-emerald-500" },
      { key: "archived", label: "Archived", accent: "border-slate-500" },
    ],
    startLabel: "Enrollment from",
    endLabel: "Enrollment to",
    filters: [
      { key: "course", label: "Course name" },
      { key: "batch", label: "Class / batch name" },
      { key: "status", label: "Status", type: "select", options: [{ value: "true", label: "Active" }, { value: "false", label: "Inactive" }] },
      { key: "gender", label: "Gender", type: "select", options: [{ value: "male", label: "Male" }, { value: "female", label: "Female" }] },
    ],
    columns: [
      { key: "role_number", label: "Student No." },
      { key: "name", label: "Student" },
      { key: "f_name", label: "Father Name" },
      { key: "parent_mobile_number", label: "Parent Mobile" },
      { key: "enrollment_date", label: "Enrollment Date" },
      { key: "is_active", label: "Active", render: (row) => (row.is_active ? "Yes" : "No") },
    ],
  },
  teachers: {
    slug: "teachers",
    title: "Teachers Report",
    endpoint: "/v1/reports/teachers/",
    description: "Review teacher headcount by department, employment status, and joining date.",
    chartKey: "teacher_departments",
    chartTitle: "Teacher Department Distribution",
    stats: [
      { key: "teachers", label: "Teachers", accent: "border-sky-500" },
      { key: "active", label: "Active", accent: "border-emerald-500" },
      { key: "inactive", label: "Inactive", accent: "border-red-500" },
      { key: "departments", label: "Departments", accent: "border-indigo-500" },
    ],
    startLabel: "Joined from",
    endLabel: "Joined to",
    filters: [
      { key: "department", label: "Department" },
      { key: "subject", label: "Subject" },
      { key: "employment_status", label: "Employment Status", type: "select", options: [{ value: "true", label: "Active" }, { value: "false", label: "Inactive" }] },
    ],
    columns: [
      { key: "full_name", label: "Teacher" },
      { key: "email_address", label: "Email" },
      { key: "phone_number", label: "Phone" },
      { key: "subject", label: "Subject" },
      { key: "department", label: "Department" },
      { key: "is_active", label: "Active", render: (row) => (row.is_active ? "Yes" : "No") },
    ],
  },
  inventory: {
    slug: "inventory",
    title: "Inventory Report",
    endpoint: "/v1/reports/inventory/",
    description: "Monitor stock levels, categories, suppliers, low-stock items, and inventory value.",
    chartKey: "stock_distribution",
    chartTitle: "Inventory Stock Distribution",
    dateFilter: false,
    stats: [
      { key: "items", label: "Items", accent: "border-sky-500" },
      { key: "low_stock", label: "Low Stock", accent: "border-orange-500" },
      { key: "out_of_stock", label: "Out of Stock", accent: "border-red-500" },
      { key: "stock_value", label: "Stock Value", accent: "border-emerald-500", format: "money" },
    ],
    filters: [
      { key: "category", label: "Category", type: "select", options: inventoryCategories },
      { key: "low_stock", label: "Low Stock", type: "select", options: [{ value: "true", label: "Low stock only" }] },
      { key: "supplier", label: "Supplier" },
    ],
    columns: [
      { key: "item_name", label: "Item" },
      { key: "sku", label: "SKU" },
      { key: "category", label: "Category" },
      { key: "quantity", label: "Qty" },
      { key: "minimum_stock", label: "Min Stock" },
      { key: "status", label: "Status" },
      { key: "supplier", label: "Supplier" },
      { key: "selling_price", label: "Price" },
    ],
  },
  stationerySales: {
    slug: "stationery-sales",
    title: "Stationery Sales Report",
    endpoint: "/v1/reports/stationery-sales/",
    description: "Analyze stationery sale receipts by product, cashier, date range, and payment status.",
    chartKey: "stationery_sales_trends",
    chartTitle: "Stationery Sales Trends",
    stats: [
      { key: "sales", label: "Sales", accent: "border-sky-500" },
      { key: "total_sales", label: "Total Sales", accent: "border-emerald-500", format: "money" },
      { key: "paid_sales", label: "Paid Sales", accent: "border-cyan-600" },
    ],
    filters: [
      { key: "product", label: "Product name" },
      { key: "cashier", label: "Cashier username" },
      { key: "payment_method", label: "Payment Status", type: "select", options: paymentStatusOptions },
    ],
    columns: [
      { key: "receipt_number", label: "Receipt" },
      { key: "date", label: "Date" },
      { key: "total", label: "Total" },
      { key: "payment_status", label: "Payment Status" },
      { key: "created_by__username", label: "Cashier" },
    ],
  },
};
