# Generated by Django 5.2 on 2025-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='className',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'className')},
        ),
    ]
