# Generated by Django 5.2 on 2025-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_marks_classname_alter_marks_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'className', 'exam_type')},
        ),
        migrations.AddField(
            model_name='marks',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=50),
        ),
    ]
