# Generated by Django 5.2 on 2025-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_marks_unique_together_marks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
