# Generated by Django 5.2 on 2025-09-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_marks_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
