# Generated by Django 5.2 on 2025-09-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assignment_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assigmment',
            new_name='assignment',
        ),
    ]
