# Generated by Django 5.2 on 2026-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
