# Generated by Django 5.2 on 2026-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tenant_is_active_tenant_subscription_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=15),
        ),
    ]
