# Generated by Django 5.2 on 2026-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_user_is_super_admin_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
