# Generated by Django 5.2 on 2026-06-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_classes_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='student_number',
        ),
        migrations.AddField(
            model_name='students',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
