# Generated by Django 5.2 on 2026-07-06 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_data_backfill_roles_courses_enrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custom_role',
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='app.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='app.students'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='app.classes'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='app.classes'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='app.students'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='roomOfClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='app.roomofclass'),
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='app.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='app.students'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='app.role'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='app.course'),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fee_plan', to='app.course'),
        ),
        migrations.RemoveField(
            model_name='students',
            name='studentClass',
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment', 'enrollment')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['batch', 'assessment_date'], name='app_assessm_batch_i_9f4488_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['enrollment', 'assessment'], name='app_assessm_enrollm_4930bb_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['course', 'batch'], name='app_assessm_course__a6069b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'status'], name='app_enrollm_tenant__ce9028_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='app_enrollm_student_c97ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['batch', 'status'], name='app_enrollm_batch_i_282d57_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='app_enrollm_course__37e4f8_idx'),
        ),
    ]
