# Generated by Django 5.2 on 2026-07-06 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_enrollment_billing(apps, schema_editor):
    Enrollment = apps.get_model("app", "Enrollment")
    EnrollmentBillingProfile = apps.get_model("app", "EnrollmentBillingProfile")
    FeePlan = apps.get_model("app", "FeePlan")
    Invoice = apps.get_model("app", "Invoice")
    Payment = apps.get_model("app", "Payment")

    for enrollment in Enrollment.objects.select_related("student", "course", "batch").all():
        plan = (
            FeePlan.objects.filter(tenant=enrollment.tenant, course=enrollment.course, batch=enrollment.batch, is_active=True).first()
            or FeePlan.objects.filter(tenant=enrollment.tenant, course=enrollment.course, batch__isnull=True, is_active=True).first()
        )
        if plan:
            EnrollmentBillingProfile.objects.get_or_create(
                tenant=enrollment.tenant,
                enrollment=enrollment,
                defaults={
                    "fee_plan": plan,
                    "billing_start_date": enrollment.enrollment_date or django.utils.timezone.localdate(),
                    "billing_status": "active",
                },
            )

    for invoice in Invoice.objects.select_related("student").all():
        enrollment = (
            Enrollment.objects.filter(tenant=invoice.tenant, student=invoice.student, status="active").order_by("-enrollment_date").first()
            or Enrollment.objects.filter(tenant=invoice.tenant, student=invoice.student).order_by("-enrollment_date").first()
        )
        fields = ["billing_month", "billing_year", "monthly_fee", "total_amount"]
        invoice.billing_month = invoice.month
        invoice.billing_year = invoice.year
        invoice.monthly_fee = invoice.amount
        invoice.total_amount = invoice.final_amount
        if enrollment:
            invoice.enrollment_id = enrollment.id
            invoice.course_id = enrollment.course_id
            invoice.batch_id = enrollment.batch_id
            fields.extend(["enrollment", "course", "batch"])
        invoice.save(update_fields=fields)

    for payment in Payment.objects.select_related("invoice").all():
        payment.student_id = payment.invoice.student_id
        payment.enrollment_id = payment.invoice.enrollment_id
        payment.amount = payment.amount_paid
        payment.save(update_fields=["student", "enrollment", "amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_finalize_enrollment_refactor_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scholarship', models.CharField(blank=True, max_length=150)),
                ('billing_start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('billing_end_date', models.DateField(blank=True, null=True)),
                ('billing_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['enrollment__student__name', 'enrollment__course__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='feeplan',
            options={'ordering': ['course__name', 'batch__name', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-billing_year', '-billing_month', 'student__name']},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='app.classes'),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='material_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='app.classes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='app.course'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='app.enrollment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.enrollment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.students'),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='app.course'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'enrollment', 'billing_month', 'billing_year')},
        ),
        migrations.AddIndex(
            model_name='feeplan',
            index=models.Index(fields=['course', 'batch'], name='app_feeplan_course__9d125e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['enrollment', 'billing_year', 'billing_month'], name='app_invoice_enrollm_b31b38_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['course', 'batch'], name='app_invoice_course__fadad6_idx'),
        ),
        migrations.AddField(
            model_name='enrollmentbillingprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentbillingprofile',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_profile', to='app.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentbillingprofile',
            name='fee_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_profiles', to='app.feeplan'),
        ),
        migrations.AddField(
            model_name='enrollmentbillingprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='app.tenant'),
        ),
        migrations.AddIndex(
            model_name='enrollmentbillingprofile',
            index=models.Index(fields=['tenant', 'billing_status'], name='app_enrollm_tenant__f858d0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentbillingprofile',
            index=models.Index(fields=['fee_plan'], name='app_enrollm_fee_pla_215402_idx'),
        ),
        migrations.RunPython(populate_enrollment_billing, migrations.RunPython.noop),
    ]
