# Generated by Codex on 2026-07-06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_ledger_metadata(apps, schema_editor):
    StudentLedgerEntry = apps.get_model("app", "StudentLedgerEntry")
    for entry in StudentLedgerEntry.objects.select_related("invoice", "payment").all():
        if entry.payment_id:
            entry.transaction_type = "payment_received"
            entry.reference_number = entry.payment.receipt_number
        elif entry.invoice_id:
            entry.transaction_type = "invoice_generated"
            entry.reference_number = entry.invoice.invoice_number
        else:
            entry.transaction_type = "adjustment"
        entry.transaction_date = entry.created_at.date() if entry.created_at else django.utils.timezone.localdate()
        entry.save(update_fields=["transaction_type", "reference_number", "transaction_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_enrollmentbillingprofile_alter_feeplan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentledgerentry",
            name="reference_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="studentledgerentry",
            name="transaction_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="studentledgerentry",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("invoice_generated", "Invoice Generated"),
                    ("invoice_updated", "Invoice Updated"),
                    ("payment_received", "Payment Received"),
                    ("partial_payment", "Partial Payment"),
                    ("discount_applied", "Discount Applied"),
                    ("scholarship_applied", "Scholarship Applied"),
                    ("late_fee_added", "Late Fee Added"),
                    ("invoice_cancelled", "Invoice Cancelled"),
                    ("refund", "Refund"),
                    ("adjustment", "Adjustment"),
                ],
                default="adjustment",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="studentledgerentry",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="app.students"),
        ),
        migrations.AlterModelOptions(
            name="studentledgerentry",
            options={"ordering": ["student", "transaction_date", "created_at"]},
        ),
        migrations.AddIndex(
            model_name="studentledgerentry",
            index=models.Index(fields=["transaction_type"], name="app_student_transac_0d871e_idx"),
        ),
        migrations.AddIndex(
            model_name="studentledgerentry",
            index=models.Index(fields=["reference_number"], name="app_student_referen_28a544_idx"),
        ),
        migrations.RunPython(backfill_ledger_metadata, migrations.RunPython.noop),
    ]
