# Generated by Codex on 2026-07-07

import django.db.models.deletion
from django.db import migrations, models


def snapshot_existing_profiles(apps, schema_editor):
    EnrollmentBillingProfile = apps.get_model("app", "EnrollmentBillingProfile")
    for profile in EnrollmentBillingProfile.objects.select_related("fee_plan", "enrollment").all():
        plan = profile.fee_plan
        profile.fee_plan_name = str(plan)
        profile.monthly_fee = plan.monthly_fee
        profile.registration_fee = plan.registration_fee
        profile.material_fee = plan.material_fee
        profile.exam_fee = plan.exam_fee
        profile.discount_allowed = plan.discount_allowed
        profile.currency = plan.currency
        profile.billing_cycle = plan.billing_cycle
        profile.due_day = plan.due_day
        profile.late_fee_amount = plan.late_fee_amount
        profile.grace_period_days = plan.grace_period_days
        profile.save(
            update_fields=[
                "fee_plan_name",
                "monthly_fee",
                "registration_fee",
                "material_fee",
                "exam_fee",
                "discount_allowed",
                "currency",
                "billing_cycle",
                "due_day",
                "late_fee_amount",
                "grace_period_days",
            ]
        )


def backfill_student_roll_numbers(apps, schema_editor):
    Students = apps.get_model("app", "Students")
    for student in Students.objects.filter(role_number=""):
        year = student.enrollment_date.year if student.enrollment_date else 2026
        student.role_number = f"ST{year}{int(student.student_number or student.id):05d}"
        student.save(update_fields=["role_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_student_ledger_accounting_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="billing_cycle",
            field=models.CharField(default="monthly", max_length=20),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="discount_allowed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="due_day",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="exam_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="fee_plan_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="grace_period_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="late_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="material_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="monthly_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="enrollmentbillingprofile",
            name="registration_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("completed", "Completed"),
                    ("dropped", "Dropped"),
                    ("transferred", "Transferred"),
                    ("cancelled", "Cancelled"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="role_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RenameIndex(
            model_name="studentledgerentry",
            new_name="app_student_transac_d9eb34_idx",
            old_name="app_student_transac_0d871e_idx",
        ),
        migrations.RenameIndex(
            model_name="studentledgerentry",
            new_name="app_student_referen_f83477_idx",
            old_name="app_student_referen_28a544_idx",
        ),
        migrations.RemoveField(
            model_name="students",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="students",
            name="total_fee",
        ),
        migrations.RunPython(snapshot_existing_profiles, migrations.RunPython.noop),
        migrations.RunPython(backfill_student_roll_numbers, migrations.RunPython.noop),
    ]
