# Generated by Codex on 2026-07-07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_erp_admission_billing_refactor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("promotion_date", models.DateField(default=django.utils.timezone.localdate)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "new_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="promotions_to", to="app.classes"),
                ),
                (
                    "new_enrollment",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="promotions_to", to="app.enrollment"),
                ),
                (
                    "old_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="promotions_from", to="app.classes"),
                ),
                (
                    "old_enrollment",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="promotions_from", to="app.enrollment"),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotions_performed", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="promotion_histories", to="app.students"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promotion_histories", to="app.tenant"),
                ),
            ],
            options={
                "ordering": ["-promotion_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="promotionhistory",
            index=models.Index(fields=["tenant", "promotion_date"], name="app_promoti_tenant__01f875_idx"),
        ),
        migrations.AddIndex(
            model_name="promotionhistory",
            index=models.Index(fields=["student", "promotion_date"], name="app_promoti_student_c91d49_idx"),
        ),
        migrations.AddIndex(
            model_name="promotionhistory",
            index=models.Index(fields=["new_class", "promotion_date"], name="app_promoti_new_cla_ab2fc1_idx"),
        ),
    ]
